version: '3.7'
services:
   web:
    build: .

   cypress:
    image: cypress/included:3.2.0
    build:
      context: .
      dockerfile: Dockerfile-cypress
    container_name: cypress
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://localhost:5000
    command: cypress run
